#ifndef MESSAGES_HPP
#define MESSAGES_HPP

namespace PyRiteMessages {

    // --- 一般的な値と操作のエラー ---
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_ADD = "うーん、「+」はこの子たちと一緒には使えないみたい…(′?ω?`)";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_SUB = "「-」で引き算しようとしたけど、この子たちじゃできないみたい…残念！";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_MUL = "「*」で掛け算、できない組み合わせだよ。ごめんね！";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_DIV = "「/」で割り算したい気持ちはわかるけど、この子たちは無理みたい…！";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_POW = "「^」で魔法をかけたかったけど、この組み合わせじゃ発動しないみたい…";
    constexpr const char* ERROR_UNSUPPORTED_COMPARISON = "この子たち、どっちが大きいか比べられないみたい。仲良しなのかな？";
    constexpr const char* ERROR_OBJECT_NOT_SUBSCRIPTABLE = "この子の中から何か取り出そうとしたけど、ポケットがないみたい！";
    constexpr const char* ERROR_OBJECT_ITEM_ASSIGNMENT_UNSUPPORTED = "この子に新しいものを入れてあげようとしたけど、嫌がられちゃった…＞＜";
    constexpr const char* ERROR_LIST_REPEAT_COUNT_INTEGER = "リストをたくさんコピーしたいときは、何回にするか数字で教えてね！";
    constexpr const char* ERROR_LIST_INDEX_MUST_BE_NUMBER = "リストの何番目か知りたいな！数字でお願い?";
    constexpr const char* ERROR_LIST_INDEX_OUT_OF_RANGE = "あれれ？リストのそんな先には何もないみたいだよ？";
    constexpr const char* ERROR_INVALID_LIST_INDEX = "その番号の子はリストにいないみたい。もう一度確認してみて！";
    constexpr const char* ERROR_HEX_STRING_PREFIX = "キラキラの16進数文字列は、「0x」から始めるとうまくいくよ！?";

    // --- ランタイムとインタプリタのエラー ---
    constexpr const char* RUNTIME_ERROR_PREFIX = "[えらーだよ！] ";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_VARIABLE_PREFIX = "あれ？「";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_VARIABLE_SUFFIX = "」っていう名前の子、どこにも見当たらないよ？";
    constexpr const char* RUNTIME_ERROR_UNCAUGHT_EXCEPTION_PREFIX = "[きゃー！例外が飛んできた！] ";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_HEADER = "ここまで、こんな感じで来たんだよ：";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_ENTRY_PREFIX = "  ここで、「";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_ENTRY_SUFFIX = "」の ";
    constexpr const char* RUNTIME_ERROR_EXECUTION_TIMEOUT_PREFIX = "時間切れになっちゃった！ (";
    constexpr const char* RUNTIME_ERROR_EXECUTION_TIMEOUT_SUFFIX = "ミリ秒)。もうちょっとだったのに！";
    constexpr const char* RUNTIME_ERROR_INVALID_ASSIGNMENT_TARGET = "ここには何かを入れることはできないみたい…ごめんね！";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_NUMBER_PREFIX = "文字列の「";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_NUMBER_SUFFIX = "」は、どうしても数字に変えられなかったよ…(′?ω?`)";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_BINARY_PREFIX = "「";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_BINARY_SUFFIX = "」をバイナリに変えられないみたい。「0x」で始まる魔法の言葉じゃないとダメなんだ！";
    constexpr const char* RUNTIME_ERROR_LIST_INIT_WITH_LIST_ONLY = "リストちゃんには、お友達のリストをあげてね！";
    constexpr const char* RUNTIME_ERROR_SET_NODE_HANDLED_BY_ASSIGNMENT = "SetNodeちゃんはAssignmentNodeちゃんにお願いしなきゃ！";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_HAVE_PROPERTIES_PREFIX = "プロパティを持てるのはインスタンスちゃんだけだよ。「";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_HAVE_PROPERTIES_SUFFIX = "」からは取ってこれないみたい…";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_CAN_SET_PROPERTIES = "プロパティを設定できるのは、インスタンスちゃんだけなんだ。";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_PROPERTY_PREFIX = "プロパティ「";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_PROPERTY_SUFFIX = "」が見つからないよ。";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_FIELD_PREFIX = "フィールド「";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_FIELD_SUFFIX = "」なんて知らない子だよ…設定できないや。";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_PREFIX = "フィールド「";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_EXPECTED = "」には「";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_GOT = "」タイプの子を入れてほしいな。でも来たのは「";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_SUFFIX = "」タイプの子だったの。";
    constexpr const char* RUNTIME_ERROR_CAN_ONLY_CALL_FUNCTIONS = "呼び出せるのは関数かメソッドだけだよ。呼び出そうとしたのは「";
    constexpr const char* RUNTIME_ERROR_CAN_ONLY_CALL_FUNCTIONS_SUFFIX = "」だったみたい。";

    // --- 関数とメソッド呼び出しのエラー ---
    constexpr const char* ERROR_ARG_COUNT_PREFIX_AT_LEAST = "」には、少なくとも ";
    constexpr const char* ERROR_ARG_COUNT_PREFIX_EXACTLY = "」には、ちょうど ";
    constexpr const char* ERROR_ARG_COUNT_PREFIX_AT_MOST = "」には、多くても ";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_BUT_GOT = " 個の引数が必要なんだけど、";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_BUT_GOT_PLURAL = " 個の引数が必要なんだけど、";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_SINGLE = " 個しかもらえなかったの…";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_PLURAL = " 個も来ちゃった…！";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_PREFIX = "引数の ";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_IN_FUNCTION = " (関数「";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_IN_METHOD = " (メソッド「";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_NAME = " (「";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_EXPECTED = "」) のタイプが違うみたい！「";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_GOT = "」タイプがよかったんだけど、「";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_SUFFIX = "」タイプの子が来ちゃった。";
    constexpr const char* ERROR_SWAP_REQUIRES_TWO_VARS = "swap()ちゃんは、2人の変数ちゃんを交換するのがお仕事だよ。";
    constexpr const char* ERROR_SWAP_ARGS_MUST_BE_VARS = "swap()ちゃんに渡すのは、変数ちゃんじゃないとダメなんだ。";
    constexpr const char* ERROR_NEW_REQUIRES_CLASS = "new()で新しい子を呼ぶときは、最初にクラスちゃんを教えてね！";


    // --- ネイティブ関数のエラー ---
    constexpr const char* NATIVE_ERROR_REQUIRES_ARGS_SUFFIX = "()ちゃんには、引数が ";
    constexpr const char* NATIVE_ERROR_REQUIRES_MIN_ARGS_SUFFIX = "()ちゃんは、最低でも ";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_NUMBER = "引数は、数字さんじゃないとダメみたい。";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_LIST = "引数は、リストちゃんじゃないとダメなんだって。";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_STRING = "引数は、文字列ちゃんじゃないとイヤみたい。";
    constexpr const char* NATIVE_ERROR_RT_ARGS = "rt()ちゃんが欲しがってる引数は、1つか2つだよ。";
    constexpr const char* NATIVE_ERROR_MIN_MAX_EMPTY = "min/maxちゃんは、ひとりぼっちじゃ寂しいみたい。引数をあげてね。";
    constexpr const char* NATIVE_ERROR_MIN_MAX_EMPTY_LIST = "空っぽのリストちゃんからは、一番大きい子も小さい子も見つけられないよ…";
    constexpr const char* NATIVE_ERROR_MIN_MAX_UNCOMPARABLE = "min/maxちゃんは、比べられる子（数字か文字列）たちじゃないと困っちゃうみたい。";
    constexpr const char* NATIVE_ERROR_TIMER_FN_NO_ARGS = "タイマーちゃんは引数を取らない、身軽な子なんだ。";
    constexpr const char* NATIVE_ERROR_LOG_POSITIVE = "log()ちゃんが計算できるのは、元気な正の数だけなんだ！";


    // --- パーサーのエラー ---
    constexpr const char* PARSE_ERROR_PREFIX = "[パースえらー] ";
    constexpr const char* PARSE_ERROR_SUFFIX = "。\n";
    constexpr const char* PARSE_ERROR_UNEXPECTED_CHAR = "ここにこんな文字があるなんて、びっくり！";
    constexpr const char* PARSE_ERROR_UNTERMINATED_STRING = "文字列が迷子みたい！おうちに帰してあげてね (\")";
    constexpr const char* PARSE_ERROR_EXPECT_EXPRESSION = "ここに式が来るはずなんだけどな…？";
    constexpr const char* PARSE_ERROR_EXPECT_VAR_NAME = "変数ちゃんのお名前を待ってるよ！";
    constexpr const char* PARSE_ERROR_EXPECT_PARAM_TYPE = "引数にはタイプ(dec, str, bin, list, any)を教えてあげてね。";
    constexpr const char* PARSE_ERROR_EXPECT_PARAM_NAME = "引数ちゃんにも、素敵なお名前を付けてあげて！";
    constexpr const char* PARSE_ERROR_DEFAULT_VALUE_LITERAL = "デフォルトの値は、シンプルで可愛いリテラル(null, 数字, 文字列, 16進数, 空っぽのリスト)にしてね。";
    constexpr const char* PARSE_ERROR_UNSUPPORTED_DEFAULT_LIST = "ごめんね、今はまだ空っぽじゃないリストをデフォルト値にできないんだ…";
    constexpr const char* PARSE_ERROR_TOO_MANY_PARAMS = "引数がたくさん！でも255人までしか入れないんだ。";
    constexpr const char* PARSE_ERROR_TOO_MANY_FIELDS = "クラスのフィールドがぎゅうぎゅう詰め！255個までにしてあげて。";
    constexpr const char* PARSE_ERROR_TOO_MANY_ARGS = "引数が多すぎるみたい！255個までなら大丈夫だよ。";
    constexpr const char* PARSE_ERROR_EXPECT_FUNC_NAME = "関数ちゃんのお名前、まだ聞いてないよ！";
    constexpr const char* PARSE_ERROR_EXPECT_METHOD_NAME = "メソッドくんのお名前、教えてほしいな！";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_NAME = "お名前のあとには「(」を付けてあげてね。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_PARAMS = "引数のお話が終わったら、「)」で閉じてあげよう。";
    constexpr const char* PARSE_ERROR_EXPECT_DO_BEFORE_BODY = "関数の本体を始める前に、「do」って言ってね！";
    constexpr const char* PARSE_ERROR_EXPECT_ENDDEF_AFTER_BODY = "関数のお話が終わったら、「enddef」で教えてね。";
    constexpr const char* PARSE_ERROR_EXPECT_CLASS_NAME = "クラスのお名前は何にする？";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_FIELDS = "フィールドのお話が終わったら、「)」を忘れないでね。";
    constexpr const char* PARSE_ERROR_EXPECT_CONTAINS_AFTER_CLASS_DEF = "クラスの定義のあとには、「contains」って続けてね。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDINS_AFTER_CLASS_BODY = "クラスのお話が終わったら、「endins」で締めくくろう！";
    constexpr const char* PARSE_ERROR_ONLY_METHODS_IN_CLASS = "クラスの「contains」ブロックの中には、メソッド定義(def)だけが入れるんだ。";
    constexpr const char* PARSE_ERROR_EXPECT_THEN_AFTER_IF = "もし(if)こうだったら…「then」どうする？";
    constexpr const char* PARSE_ERROR_EXPECT_ENDIF_AFTER_IF = "もし(if)のお話が終わったら、「endif」って教えてね。";
    constexpr const char* PARSE_ERROR_EXPECT_DO_AFTER_WHILE = "whileでくるくるする前に、「do」で始めるよ！";
    constexpr const char* PARSE_ERROR_EXPECT_ENDWHILE_AFTER_WHILE = "whileループが終わったら、「endwhile」で合図してね。";
    constexpr const char* PARSE_ERROR_EXPECT_THEN_AFTER_AWAIT = "awaitで待ったあと、「then」どうするか教えて！";
    constexpr const char* PARSE_ERROR_EXPECT_ENDAWAIT_AFTER_AWAIT = "awaitのお話が終わったら、「endawait」で教えてね。";
    constexpr const char* PARSE_ERROR_EXPECT_CATCH_AFTER_TRY = "「try」で挑戦したあとは、「catch」で受け止めてあげて。";
    constexpr const char* PARSE_ERROR_EXPECT_VAR_AFTER_CATCH = "「catch」のあとには、エラーを受け止める変数ちゃんのお名前が必要だよ。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDTRY_AFTER_TRY = "try/catch/finallyの冒険が終わったら、「endtry」でゴールだよ！";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_SAY = "「say」でおしゃべりするときは、まず「(」からだよ。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_EXPR = "式のお話が終わったら、「)」で閉じてあげてね。";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_ASK = "「ask」で質問するときも、まず「(」からスタート！";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_PROMPT = "プロンプトが終わったら、「)」で教えてね。";
    constexpr const char* PARSE_ERROR_EXPECT_RBRACKET_AFTER_LIST = "リストの仲間たちを並べたら、最後に「]」でまとめてあげよう。";
    constexpr const char* PARSE_ERROR_EXPECT_RBRACKET_AFTER_INDEX = "インデックスを教えたら、「]」で閉じるのを忘れないでね。";
    constexpr const char* PARSE_ERROR_EXPECT_PROP_NAME = "プロパティかメソッドのお名前、どっちかな？";

    // --- デバッグメッセージ ---
    // (デバッグメッセージは開発者向けなので、可愛さを少し控えめにしつつ、分かりやすくしています)
    constexpr const char* DEBUG_ENV_DEFINE = "[デバッグ:環境] 環境 ";
    constexpr const char* DEBUG_ENV_IN_ENV = " に '";
    constexpr const char* DEBUG_ENV_AS = "' を ";
    constexpr const char* DEBUG_ENV_ASSIGN = "[デバッグ:環境] '";
    constexpr const char* DEBUG_ENV_VALUE = "' に代入ちゅう = ";
    constexpr const char* DEBUG_ENV_ASSIGN_FAIL = "[デバッグ:環境] ";
    constexpr const char* DEBUG_ENV_TRY_ENCLOSING = " に代入できなかった…外側の環境 ";
    constexpr const char* DEBUG_ENV_GET = "[デバッグ:環境] '";
    constexpr const char* DEBUG_ENV_FROM_ENV = "' を環境 ";
    constexpr const char* DEBUG_ENV_FOUND = "  '";
    constexpr const char* DEBUG_ENV_GET_FAIL = "  ";
    constexpr const char* DEBUG_PARSER_START = "[デバッグ:パーサー] パース始めるよー！";
    constexpr const char* DEBUG_PARSER_PARSING_DECL = "[デバッグ:パーサー] 宣言をパースちゅう (今のトークン: ";
    constexpr const char* DEBUG_PARSER_PARSING_PARAM = "[デバッグ:パーサー] 引数を読んでるよ…";
    constexpr const char* DEBUG_PARSER_PARSING_DEFAULT_VAL_FOR = "  '";
    constexpr const char* DEBUG_PARSER_PARSED_PARAM = "  引数、読めた！: ";
    constexpr const char* DEBUG_PARSER_WITH_DEFAULT = " (デフォルト値つき)";
    constexpr const char* DEBUG_PARSER_PARSING_VAR_DECL = "[デバッグ:パーサー] 変数宣言をパースちゅう…";
    constexpr const char* DEBUG_PARSER_PARSING_FUNC_DEF = "[デバッグ:パーサー] 関数定義をパースちゅう…";
    constexpr const char* DEBUG_PARSER_PARSING_METHOD_DEF = "[デバッグ:パーサー] メソッド定義をパースちゅう…";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_FUNC = "  関数 '";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_METHOD = "  メソッド '";
    constexpr const char* DEBUG_PARSER_PARSING_CLASS_DEF = "[デバッグ:パーサー] クラス定義をパースちゅう…";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_CLASS = "  クラス '";
    constexpr const char* DEBUG_PARSER_PARSING_ASSIGNMENT = "[デバッグ:パーサー] 代入式をパースちゅう…";
    constexpr const char* DEBUG_PARSER_PARSING_CALL = "[デバッグ:パーサー] 関数呼び出しをパースちゅう…";
    constexpr const char* DEBUG_PARSER_PARSING_SUBSCRIPT = "[デバッグ:パーサー] 添字アクセスをパースちゅう…";
    constexpr const char* DEBUG_PARSER_PARSING_GET = "[デバッグ:パーサー] プロパティ/メソッドアクセスをパースちゅう…";
    constexpr const char* DEBUG_INTERP_START = "[デバッグ:インタプリタ] ";
    constexpr const char* DEBUG_INTERP_STATEMENTS = " 個の文を解釈するね。";
    constexpr const char* DEBUG_INTERP_EXEC_TOP_LEVEL = "[デバッグ:インタプリタ] === トップレベル文 ";
    constexpr const char* DEBUG_INTERP_AT_LINE = " (";
    constexpr const char* DEBUG_INTERP_END_EXEC_STMT = "行目) を実行するよ ===";
    constexpr const char* DEBUG_INTERP_DONE = "[デバッグ:インタプリタ] 解釈、おわったよ！";
    constexpr const char* DEBUG_INTERP_EXEC_STMT_TYPE = "[デバッグ:インタプリタ] タイプ ";
    constexpr const char* DEBUG_INTERP_EVAL_EXPR_TYPE = "[デバッグ:インタプリタ] タイプ ";
    constexpr const char* DEBUG_INTERP_BLOCK_ENTER = "[デバッグ:インタプリタ] ---> 新しい世界(ブロック)に入るよ。環境: ";
    constexpr const char* DEBUG_INTERP_BLOCK_PREVIOUS = " 前の世界: ";
    constexpr const char* DEBUG_INTERP_BLOCK_EXIT_EXCEPTION = "[デバッグ:インタプリタ] <--- 例外発生！世界(ブロック)から脱出するね。環境を ";
    constexpr const char* DEBUG_INTERP_BLOCK_EXIT = "[デバッグ:インタプリタ] <--- 世界(ブロック)から出るよ。環境を ";
    constexpr const char* DEBUG_EXEC_LITERAL_NODE = "[デバッグ:実行] LiteralNodeを評価ちゅう。値: ";
    constexpr const char* DEBUG_EXEC_LIST_LITERAL_NODE = "[デバッグ:実行] ListLiteralNodeを評価ちゅう (";
    constexpr const char* DEBUG_EXEC_LIST_LITERAL_NODE_ELEMENTS = " 人の仲間たち)。";
    constexpr const char* DEBUG_EXEC_VAR_NODE = "[デバッグ:実行] VariableNode '";
    constexpr const char* DEBUG_EXEC_ASSIGN_NODE = "[デバッグ:実行] AssignmentNodeを実行ちゅう。代入する値: ";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_VAR = "  入れる場所は VariableNode: '";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_SUBSCRIPT = "  入れる場所は SubscriptNode だね。";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_GET = "  入れる場所は GetNode: プロパティ '";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_INIT = "[デバッグ:実行] '";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_WITH_INIT = "' のVarDeclarationNodeを実行ちゅう（初期値あり）。";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_NO_INIT = "' のVarDeclarationNodeを実行ちゅう（初期値なし）。";
    constexpr const char* DEBUG_EXEC_VAR_DECL_DECLARED_TYPE = "  宣言されたタイプ: ";
    constexpr const char* DEBUG_EXEC_VAR_DECL_INITIAL_VALUE = "。最初の値: ";
    constexpr const char* DEBUG_EXEC_VAR_DECL_FINAL_VALUE = "  タイプを合わせて、最終的な値はこれ！: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP = "[デバッグ:実行] BinaryOpNodeを評価ちゅう（演算子: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP_LEFT = "  左の子: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP_RIGHT = ", 右の子: ";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE = "[デバッグ:実行] SubscriptNodeを評価ちゅう。";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE_OBJ = "  オブジェクト: ";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE_IDX = ", インデックス: ";
    constexpr const char* DEBUG_EXEC_IF_NODE = "[デバッグ:実行] IfStatementNodeを実行ちゅう。条件はどうかな…";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_TRUE = "  条件は本当だった！";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_FALSE = "  条件はうそだった…";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_VALUE = " (";
    constexpr const char* DEBUG_EXEC_IF_THEN = "  'then' の道を進むよ。";
    constexpr const char* DEBUG_EXEC_IF_ELSE = "  'else' の道を進むよ。";
    constexpr const char* DEBUG_EXEC_WHILE_NODE = "[デバッグ:実行] WhileStatementNodeを実行ちゅう。";
    constexpr const char* DEBUG_EXEC_WHILE_CONDITION_TRUE = "  Whileループの条件は本当！";
    constexpr const char* DEBUG_EXEC_WHILE_CONDITION_FALSE = "  Whileループの条件はうそ！";
    constexpr const char* DEBUG_EXEC_WHILE_FINALLY = "  whileループの 'finally' ブロックを実行するよ。";
    constexpr const char* DEBUG_EXEC_AWAIT_NODE = "[デバッグ:実行] AwaitStatementNodeを実行ちゅう。条件がそろうのを待ってる…";
    constexpr const char* DEBUG_EXEC_AWAIT_SATISFIED = "  Awaitの条件がそろった！ 'then' の道へ進むよ。";
    constexpr const char* DEBUG_EXEC_SAY_NODE = "[デバッグ:実行] SayNodeを実行ちゅう。";
    constexpr const char* DEBUG_EXEC_SAY_VALUE = "  おしゃべりする内容: ";
    constexpr const char* DEBUG_EXEC_FUNC_DEF_NODE = "[デバッグ:実行] '";
    constexpr const char* DEBUG_EXEC_CLASS_DEF_NODE = "[デバッグ:実行] クラス '";
    constexpr const char* DEBUG_EXEC_CLASS_DEF_PROCESSING_METHOD = "  メソッド '";
    constexpr const char* DEBUG_EXEC_GET_NODE = "[デバッグ:実行] プロパティ '";
    constexpr const char* DEBUG_EXEC_GET_NODE_OBJECT_EVAL = "  オブジェクトを評価した結果: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE = "[デバッグ:実行] CallNodeを実行ちゅう（";
    constexpr const char* DEBUG_EXEC_CALL_NODE_EVAL_CALLEE = "行目）。呼び出す子を評価するね…";
    constexpr const char* DEBUG_EXEC_CALL_NODE_CALLEE_EVAL = "  呼び出す子を評価した結果: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_EVAL_ARGS = "  ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ARGS = " 個の引数を評価ちゅう…";
    constexpr const char* DEBUG_EXEC_CALL_NODE_NATIVE = "  ネイティブ関数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_USER = "  ユーザー関数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BINDING_ARGS = "    ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ARGS_TO = " 個の引数を ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_PARAMS = " 個の仮引数にセットするね（";
    constexpr const char* DEBUG_EXEC_CALL_NODE_REQUIRED = " 個が必要）。";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BINDING_PARAM = "      仮引数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_TO_ARG = "' に実引数 ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_PUSH_STACK = "    '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_TO_STACK = "' をコールスタックに積んだよ。";
    constexpr const char* DEBUG_EXEC_CALL_NODE_POP_STACK = "    '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_FROM_STACK = "' をコールスタックから取ってきたよ。戻り値: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BOUND_METHOD = "  バインド済みメソッド '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ON_INSTANCE = "' をインスタンス ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_DEFINE_THIS = "    メソッドの世界に 'this' を用意するね。";
    constexpr const char* DEBUG_EXEC_RETURN_NODE = "[デバッグ:実行] ReturnNodeを実行ちゅう。ReturnValueExceptionを投げるね。値: ";
    constexpr const char* DEBUG_EXEC_RAISE_NODE = "[デバッグ:実行] RaiseNodeを実行ちゅう。PyRiteRaiseExceptionを投げるよ！ペイロード: ";
    constexpr const char* DEBUG_EXEC_TRY_NODE = "[デバッグ:実行] TryCatchNodeを実行ちゅう。「try」ブロックに挑戦！";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_PYRITE = "  「try」ブロックでPyRiteRaiseExceptionをキャッチしたよ！ペイロード: ";
    constexpr const char* DEBUG_EXEC_TRY_EXEC_CATCH = "。「catch」ブロックを実行するね。";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_RUNTIME = "  「try」ブロックでRuntimeErrorをキャッチしたよ: ";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_UNEXPECTED = "  「catch」ブロックで予期せぬ例外をキャッチ！「finally」のあとでもう一回投げるね。";
    constexpr const char* DEBUG_EXEC_TRY_EXEC_FINALLY = "  「finally」ブロックを実行するよ。";
    constexpr const char* DEBUG_EXEC_TRY_RETHROWING = "  「catch」ブロックから例外を再スロー！";
    constexpr const char* DEBUG_EXEC_TRY_DONE = "  TryCatchNodeの実行、おしまい！";
    constexpr const char* DEBUG_EXEC_EXPR_STMT_NODE = "[デバッグ:実行] ExpressionStatementNodeを実行ちゅう。";
    constexpr const char* DEBUG_INSTANCE_CREATING = "[デバッグ:インスタンス] '";
    constexpr const char* DEBUG_INSTANCE_NEW_ENV = "' のインスタンスを作るよ。新しい環境を用意します。囲んでいる環境: ";
    constexpr const char* DEBUG_INSTANCE_INIT_FIELD = "  フィールド '";
    constexpr const char* DEBUG_INSTANCE_WITH_DEFAULT = "' にデフォルト値 ";
    constexpr const char* DEBUG_INSTANCE_GET_PROP = "[デバッグ:インスタンス] プロパティ '";
    constexpr const char* DEBUG_INSTANCE_FROM = "' をインスタンス '";
    constexpr const char* DEBUG_INSTANCE_CHECK_FIELDS = "' から探すね。  まずインスタンスのフィールドをチェック…";
    constexpr const char* DEBUG_INSTANCE_PROP_NOT_IN_FIELDS = "  プロパティ '";
    constexpr const char* DEBUG_INSTANCE_CHECK_METHODS = "' はフィールドにいなかった。クラスのメソッドを探すね…";
    constexpr const char* DEBUG_INSTANCE_FOUND_METHOD = "  メソッド '";
    constexpr const char* DEBUG_INSTANCE_CREATING_BOUND_METHOD = "' を見つけた！バインド済みメソッドを作るよ。";
    constexpr const char* DEBUG_INSTANCE_SET_PROP = "[デバッグ:インスタンス] プロパティ '";
    constexpr const char* DEBUG_INSTANCE_FOR = "' をインスタンス '";
    constexpr const char* DEBUG_INSTANCE_TO_VALUE = "' に設定するよ。値 ";
    constexpr const char* DEBUG_INSTANCE_FOUND_FIELD = "  フィールド '";
    constexpr const char* DEBUG_INSTANCE_TYPE_CHECKING = "' を発見。タイプをチェックするね… 欲しいのは: ";
    constexpr const char* DEBUG_INSTANCE_TYPE_CHECK_OK = "  タイプチェックOK！フィールドの値を設定するよ。";

    // --- REPL と Main ---
    constexpr const char* REPL_WELCOME_BANNER_1 = "PyRite インタプリタ v0.19.0 へようこそ (tags/v0.19.0, compilers/TDM-GCC 4.9.2 64-bit Release)";
    constexpr const char* REPL_WELCOME_BANNER_DEBUG = " [デバッグモード]だよ";
    constexpr const char* REPL_WELCOME_BANNER_2 = ".\n";
    constexpr const char* REPL_WELCOME_BANNER_3 = "'run()'でコードを実行、'compile()'でコンパイル、'halt()'でまたね！ 'about()'で自己紹介するよ。\n";
    constexpr const char* REPL_HALTED = "インタプリタを終了します。また遊んでね！";
    constexpr const char* REPL_NO_CODE_TO_RUN = "実行するコードが何もないみたい。";
    constexpr const char* REPL_TICK_ARG_ERROR = "[えらーだよ！] run()の'tick'引数は、ブール値(0/1かfalse/true)にしてね。";
    constexpr const char* REPL_LIMIT_ARG_ERROR_LITERAL = "[えらーだよ！] run()の'limit'引数は、数字じゃなきゃダメだよ。";
    constexpr const char* REPL_LIMIT_ARG_ERROR_INVALID = "[えらーだよ！] run()の'limit'引数がなんだか変だよ？";
    constexpr const char* REPL_EXECUTION_TIME_PREFIX = "コードの実行にかかった時間: ";
    constexpr const char* REPL_EXECUTION_TIME_SUFFIX = "ミリ秒でした！";
    constexpr const char* ABOUT_HEADER_FOOTER = "----------------------------------------\n";
    constexpr const char* ABOUT_LINE_1 = " PyRite 言語インタプリタ v0.19.0";
    constexpr const char* ABOUT_LINE_2 = "\n (c) 2024-2025. DarkstarXD. All Rights Reserved.\n";
    constexpr const char* ABOUT_LINE_3 = " 魔法みたいにシンプルなプログラミング言語だよ！\n";
    constexpr const char* MAIN_USAGE_ERROR = "使い方: ";
    constexpr const char* MAIN_USAGE_ERROR_SCRIPT = " [script.src]";
    constexpr const char* MAIN_FILE_OPEN_ERROR = "エラー: ファイル「";

    // --- コンパイル ---
    constexpr const char* COMPILE_SYNTAX_ERROR = "文法エラー: 呼び出しには「()」が必要だよ。";
    constexpr const char* COMPILE_ARG_SYNTAX_ERROR = "文法エラー: 引数は「キー=値」の形でお願い！";
    constexpr const char* COMPILE_ERROR_PREFIX = "[コンパイルえらー] ";
    constexpr const char* COMPILE_ERROR_SUFFIX = "。";
    constexpr const char* COMPILE_BUFFER_EMPTY = "バッファが空っぽだから、コンパイルできないよ。";
    constexpr const char* COMPILE_CANNOT_OPEN_SOURCE = "ソースファイルが開けないみたい: ";
    constexpr const char* COMPILE_CANNOT_OPEN_TEMPLATE = "コンパイラのテンプレートファイルが開けなかった…: ";
    constexpr const char* COMPILE_TEMPLATE_PLACEHOLDER_MISSING = "template.cppの中に、魔法の呪文「WRITE_SRC_CODE_HERE」が見つからないよ！";
    constexpr const char* COMPILE_TRANSLATION_TARGET = "変換ターゲット: ";
    constexpr const char* COMPILE_CANNOT_OPEN_TEMP_WRITE = "一時ファイルに書き込めなかった（パスか権限をチェックしてみてね）: ";
    constexpr const char* COMPILE_WRITE_TEMP_FAILED = "一時ファイルへの書き込みに失敗しちゃった（ディスクがいっぱいかも？）: ";
    constexpr const char* COMPILE_COMMAND_INFO = "これから使うコンパイルコマンド: ";
    constexpr const char* COMPILE_SUCCESS_PREFIX = " ";
    constexpr const char* COMPILE_SUCCESS_TOOK = " のコンパイルに成功したよ！（かかった時間 ";
    constexpr const char* COMPILE_SUCCESS_SECONDS = " 秒）。出力先: ";
    constexpr const char* COMPILE_FAILURE_PREFIX = " ";
    constexpr const char* COMPILE_FAILURE_SUFFIX = " のコンパイルに失敗しちゃった（コンパイラエラー）";
}

#endif // MESSAGES_HPP
